CREATE SCHEMA IF NOT EXISTS dev;

CREATE TABLE dev.customers (
    customer_id              text NOT NULL
        CONSTRAINT customers_pk PRIMARY KEY,
    days_since_first_order   integer,
    days_since_last_order    integer,
    is_newsletter_subscriber boolean,
    orders                   integer,
    items                    integer,
    cancels                  integer,
    returns                  integer,
    different_addresses      integer,
    shipping_addresses       integer,
    devices                  integer,
    vouchers                 integer,
    cc_payments              integer,
    paypal_payments          integer,
    afterpay_payments        integer,
    apple_payments           integer,
    female_items             integer,
    male_items               integer,
    unisex_items             integer,
    wapp_items               integer,
    wftw_items               integer,
    mapp_items               integer,
    wacc_items               integer,
    macc_items               integer,
    mftw_items               integer,
    wspt_items               integer,
    mspt_items               integer,
    curvy_items              integer,
    sacc_items               integer,
    msite_orders             integer,
    desktop_orders           integer,
    android_orders           integer,
    ios_orders               integer,
    other_device_orders      integer,
    work_orders              integer,
    home_orders              integer,
    parcelpoint_orders       integer,
    other_collection_orders  integer,
    average_discount_onoffer numeric,
    average_discount_used    numeric,
    revenue                  numeric
);
