INSERT INTO dev.customers(
    customer_id, days_since_first_order, days_since_last_order, is_newsletter_subscriber, orders, items, cancels,
    returns, different_addresses, shipping_addresses, devices, vouchers, cc_payments, paypal_payments,
    afterpay_payments, apple_payments, female_items, male_items, unisex_items, wapp_items, wftw_items, mapp_items,
    wacc_items, macc_items, mftw_items, wspt_items, mspt_items, curvy_items, sacc_items, msite_orders, desktop_orders,
    android_orders, ios_orders, other_device_orders, work_orders, home_orders, parcelpoint_orders,
    other_collection_orders, average_discount_onoffer, average_discount_used, revenue
)
SELECT *
FROM tmp_table
ON CONFLICT ON CONSTRAINT customers_pk DO UPDATE SET days_since_first_order   = excluded.days_since_first_order,
                                                     days_since_last_order    = excluded.days_since_last_order,
                                                     is_newsletter_subscriber = excluded.is_newsletter_subscriber,
                                                     orders                   = excluded.orders,
                                                     items                    = excluded.items,
                                                     cancels                  = excluded.cancels,
                                                     returns                  = excluded.returns,
                                                     different_addresses      = excluded.different_addresses,
                                                     shipping_addresses       = excluded.shipping_addresses,
                                                     devices                  = excluded.devices,
                                                     vouchers                 = excluded.vouchers,
                                                     cc_payments              = excluded.cc_payments,
                                                     paypal_payments          = excluded.paypal_payments,
                                                     afterpay_payments        = excluded.afterpay_payments,
                                                     apple_payments           = excluded.apple_payments,
                                                     female_items             = excluded.female_items,
                                                     male_items               = excluded.male_items,
                                                     unisex_items             = excluded.unisex_items,
                                                     wapp_items               = excluded.wapp_items,
                                                     wftw_items               = excluded.wftw_items,
                                                     mapp_items               = excluded.mapp_items,
                                                     wacc_items               = excluded.wacc_items,
                                                     macc_items               = excluded.macc_items,
                                                     mftw_items               = excluded.mftw_items,
                                                     wspt_items               = excluded.wspt_items,
                                                     mspt_items               = excluded.mspt_items,
                                                     curvy_items              = excluded.curvy_items,
                                                     sacc_items               = excluded.sacc_items,
                                                     msite_orders             = excluded.msite_orders,
                                                     desktop_orders           = excluded.desktop_orders,
                                                     android_orders           = excluded.android_orders,
                                                     ios_orders               = excluded.ios_orders,
                                                     other_device_orders      = excluded.other_collection_orders,
                                                     work_orders              = excluded.work_orders,
                                                     home_orders              = excluded.home_orders,
                                                     parcelpoint_orders       = excluded.parcelpoint_orders,
                                                     other_collection_orders  = excluded.other_collection_orders,
                                                     average_discount_onoffer = excluded.average_discount_onoffer,
                                                     average_discount_used    = excluded.average_discount_used,
                                                     revenue                  = excluded.revenue;
